spring:
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SALab?useSSL=false
    username: SALab
    password: SALab
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy