DROP TABLE IF EXISTS SurrogateKeys;
DROP TABLE IF EXISTS Resources;
DROP TABLE IF EXISTS ResourceGroups;
DROP TABLE IF EXISTS RMemberInterests;
DROP TABLE IF EXISTS RMemberPublications;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Interests;
DROP TABLE IF EXISTS Publications;
DROP TABLE IF EXISTS Members;

CREATE TABLE Members(
  ID INTEGER NOT NULL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  KoreanName VARCHAR(255) NOT NULL,
  Degree VARCHAR(255) NOT NULL,
  Link VARCHAR(255),
  EnterDate DATE NOT NULL,
  Graduated BOOLEAN DEFAULT FALSE,
  GraduatedDate DATE DEFAULT NULL
) Engine = InnoDB;

CREATE TABLE Publications(
  ID INTEGER NOT NULL PRIMARY KEY,
  PublicationType VARCHAR(255) NOT NULL,
  Title VARCHAR(255) NOT NULL,
  MetaData VARCHAR(255) NOT NULL,
  Date DATE NOT NULL
) Engine = InnoDB;

CREATE TABLE Interests(
  ID INTEGER NOT NULL PRIMARY KEY,
  FieldName VARCHAR(255) NOT NULL,
  FieldDesc TEXT
) Engine = InnoDB;

CREATE TABLE Courses(
  ID INTEGER NOT NULL PRIMARY KEY,
  CourseID VARCHAR(255) NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Description TEXT NOT NULL
) Engine = InnoDB;

CREATE TABLE RMemberPublications(
  ID INTEGER NOT NULL PRIMARY KEY,
  PublicationID INTEGER NOT NULL,
  MemberID INTEGER NOT NULL,
  AuthorOrder INTEGER NOT NULL
) Engine = InnoDB;

CREATE TABLE RMemberInterests(
  ID INTEGER NOT NULL PRIMARY KEY,
  InterestID INTEGER NOT NULL,
  MemberID INTEGER NOT NULL
) Engine = InnoDB;

CREATE TABLE Resources(
  ID INTEGER NOT NULL PRIMARY KEY,
  ResourceGroupID INTEGER NOT NULL,
  ResourceType VARCHAR(255) NOT NULL,
  Title TEXT NOT NULL,
  Contents TEXT NOT NULL
) Engine = InnoDB;

CREATE TABLE ResourceGroups(
  ID INTEGER NOT NULL PRIMARY KEY,
  GroupName VARCHAR(255) NOT NULL
) Engine = InnoDB;


CREATE TABLE SurrogateKeys(
  TableName VARCHAR(255) NOT NULL PRIMARY KEY,
  KeyValue BIGINT NOT NULL
) Engine = InnoDB;

ALTER TABLE RMemberPublications
  ADD CONSTRAINT FK_Publications_ID FOREIGN KEY (PublicationID) REFERENCES Publications(ID),
  ADD CONSTRAINT FK_Members_ID FOREIGN KEY (MemberID) REFERENCES Members(ID);

ALTER TABLE RMemberInterests
  ADD CONSTRAINT FK_Interests_ID FOREIGN KEY (InterestID) REFERENCES Interests(ID),
  ADD CONSTRAINT FK_Interests_Members_ID FOREIGN KEY (MemberID) REFERENCES Members(ID);

ALTER TABLE Resources
  ADD CONSTRAINT FK_Resources_ResourceGroupID FOREIGN KEY (ResourceGroupID) REFERENCES ResourceGroups(ID);
